// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdpsbHoaeq_0tI44gdcawQHbg5ewvxohA',
    appId: '1:345699600155:web:7717c3b6e8993cfbe075be',
    messagingSenderId: '345699600155',
    projectId: 'flutter-auth-a98d8',
    authDomain: 'flutter-auth-a98d8.firebaseapp.com',
    storageBucket: 'flutter-auth-a98d8.firebasestorage.app',
    measurementId: 'G-DVVXKCDEGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_gCOPVeCj5Iv5MLaDEmWWNvx0om7Q3xA',
    appId: '1:345699600155:android:81ed4cfe475f9fa3e075be',
    messagingSenderId: '345699600155',
    projectId: 'flutter-auth-a98d8',
    storageBucket: 'flutter-auth-a98d8.firebasestorage.app',
  );
}
